### ISSUE TITLE
Vorschlag zur Erweiterung der Webseite mit einem Modulplan

### ISSUE THREAD

**Issue by DUSAhdu** [Moritz-Tim-Widmann/Moritz-Tim-Widmann.github.io#3]
In die Webseite würde einen Modulplan gut hinpassen, bei dem man die schon abgearbeiteten Module sieht, sowie die Module die noch vor uns sind, diese sollten markiert sein bsp: Module die wir schon hatten grau Module die vor uns liegen Grün und Blau.
:)

**Comment by moritztim** [comment]
Done: 64bbff2
